CREATE TABLE `sys__operate_log` (
  `id` int(11) NOT NULL,
  `operate_desc` varchar(50) DEFAULT NULL COMMENT '日志信息描述',
  `operate_method` varchar(20) DEFAULT NULL COMMENT '目标方法',
  `log_type` varchar(10) DEFAULT NULL COMMENT '日志类型(info:操作日志,error:错误)',
  `ip_address` varchar(30) DEFAULT NULL COMMENT '请求的ip',
  `excep_name` varchar(255) DEFAULT NULL COMMENT '异常名称',
  `excep_detail` text COMMENT '异常详情',
  `parameter` text COMMENT '请求参数',
  `result` text COMMENT '请求返回的结果',
  `operate_user_id` varchar(32) DEFAULT NULL COMMENT '请求的用户id',
  `operate_user_name` varchar(255) DEFAULT NULL COMMENT '操作者名称',
  `spendTime` bigint(20) DEFAULT NULL COMMENT '消耗时间(单位：毫秒)',
  `startTime` bigint(20) DEFAULT NULL COMMENT '操作时间',
  `operate_ver` varchar(16) DEFAULT NULL COMMENT '操作版本号',
  `operate_model` varchar(64) DEFAULT NULL COMMENT '操作模块',
  `operate_type` varchar(16) DEFAULT NULL COMMENT '操作类型',
  `operate_class` varchar(255) DEFAULT NULL COMMENT '目标类名',
  `request_type` varchar(16) DEFAULT NULL COMMENT '请求方式(请求类型)',
  `base_path` varchar(128) DEFAULT NULL COMMENT '根路径',
  `uri` varchar(255) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='系统日志表';